# 🐳 Docker Compose برای HomayOMS
# 🏗️ شامل Django، PostgreSQL و pgAdmin

version: '3.8'

services:
  # 🐘 PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: homayoms_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: homayoms_db
      POSTGRES_USER: homayoms_user
      POSTGRES_PASSWORD: homayoms_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - homayoms_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homayoms_user -d homayoms_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🐘 pgAdmin - مدیریت پایگاه داده
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: homayoms_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@homayoms.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - homayoms_network
    depends_on:
      - db

  # 🐍 Django Web Application
  web:
    build: .
    container_name: homayoms_web
    restart: unless-stopped
    environment:
      # 🔐 تنظیمات امنیتی
      SECRET_KEY: your-super-secret-key-change-this-in-production
      DEBUG: 'False'
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
      
      # 🗄️ تنظیمات پایگاه داده
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: homayoms_db
      DB_USER: homayoms_user
      DB_PASSWORD: homayoms_password
      DATABASE_URL: postgresql://homayoms_user:homayoms_password@db:5432/homayoms_db
      
      # 🌐 تنظیمات CORS
      CORS_ALLOWED_ORIGINS: http://localhost:8000,http://127.0.0.1:8000
      
      # 📧 تنظیمات ایمیل (اختیاری)
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 'True'
      EMAIL_HOST_USER: your-email@gmail.com
      EMAIL_HOST_PASSWORD: your-app-password
      
      # ⏰ تنظیمات timezone
      TIME_ZONE: Asia/Tehran
      LANGUAGE_CODE: fa-ir
      
      # 📁 تنظیمات فایل‌ها
      STATIC_URL: /static/
      STATIC_ROOT: /app/staticfiles
      MEDIA_URL: /media/
      MEDIA_ROOT: /app/media
      
      # 🔧 تنظیمات Django
      DJANGO_SETTINGS_MODULE: HomayOMS.settings.production
      
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    networks:
      - homayoms_network
    depends_on:
      db:
        condition: service_healthy

# 📦 Volumes برای ذخیره داده‌ها
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local

# 🌐 Network برای ارتباط بین سرویس‌ها
networks:
  homayoms_network:
    driver: bridge 