# Generated by Django 5.2.1 on 2025-07-21 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('sms_server_url', models.URLField(default='http://192.168.1.60:5003', help_text='آدرس سرور SMS', verbose_name='آدرس سرور SMS')),
                ('api_key', models.CharField(default='ioms_sms_server_2025', help_text='کلید API برای دسترسی به سرور SMS', max_length=100, verbose_name='کلید API')),
                ('default_sender', models.CharField(default='HomayOMS', help_text='نام فرستنده پیش\u200cفرض', max_length=20, verbose_name='فرستنده پیش\u200cفرض')),
                ('verification_code_expiry', models.IntegerField(default=10, help_text='زمان انقضای کد تایید به دقیقه', verbose_name='زمان انقضای کد تایید (دقیقه)')),
                ('max_verification_attempts', models.IntegerField(default=3, help_text='حداکثر تعداد تلاش\u200cهای ناموفق', verbose_name='حداکثر تلاش\u200cهای تایید')),
                ('enable_order_notifications', models.BooleanField(default=True, help_text='فعال\u200cسازی اعلان\u200cهای وضعیت سفارش', verbose_name='اعلان\u200cهای سفارش')),
                ('enable_payment_notifications', models.BooleanField(default=True, help_text='فعال\u200cسازی اعلان\u200cهای پرداخت', verbose_name='اعلان\u200cهای پرداخت')),
                ('retry_attempts', models.IntegerField(default=3, help_text='تعداد تلاش\u200cهای مجدد در صورت شکست', verbose_name='تعداد تلاش\u200cهای مجدد')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='زمان انتظار برای پاسخ API', verbose_name='زمان انتظار (ثانیه)')),
            ],
            options={
                'verbose_name': 'تنظیمات SMS',
                'verbose_name_plural': 'تنظیمات SMS',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(help_text='نام قالب پیامک', max_length=100, verbose_name='نام قالب')),
                ('template_type', models.CharField(choices=[('VERIFICATION', '🔐 کد تایید'), ('ORDER_STATUS', '📦 وضعیت سفارش'), ('PAYMENT', '💳 پرداخت'), ('NOTIFICATION', '🔔 اطلاع\u200cرسانی'), ('MARKETING', '📢 بازاریابی')], help_text='نوع قالب پیامک', max_length=20, verbose_name='نوع قالب')),
                ('content', models.TextField(help_text='محتوای قالب با متغیرهای {variable}', verbose_name='محتوای قالب')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این قالب فعال است', verbose_name='فعال')),
                ('variables', models.JSONField(default=dict, help_text='متغیرهای مورد نیاز قالب', verbose_name='متغیرها')),
            ],
            options={
                'verbose_name': 'قالب پیامک',
                'verbose_name_plural': 'قالب\u200cهای پیامک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, help_text='شناسه یکتای ردیابی پیام', unique=True, verbose_name='شناسه ردیابی')),
                ('phone_number', models.CharField(help_text='شماره تلفن گیرنده', max_length=20, verbose_name='شماره تلفن')),
                ('message_content', models.TextField(help_text='محتوای پیام ارسالی', verbose_name='محتوای پیام')),
                ('message_type', models.CharField(choices=[('VERIFICATION', '🔐 کد تایید'), ('ORDER_STATUS', '📦 وضعیت سفارش'), ('PAYMENT', '💳 پرداخت'), ('NOTIFICATION', '🔔 اطلاع\u200cرسانی'), ('MARKETING', '📢 بازاریابی')], help_text='نوع پیام ارسالی', max_length=20, verbose_name='نوع پیام')),
                ('status', models.CharField(choices=[('PENDING', '⏳ در انتظار'), ('SENT', '✅ ارسال شده'), ('DELIVERED', '📨 تحویل داده شده'), ('FAILED', '❌ ناموفق'), ('CANCELLED', '🚫 لغو شده')], default='PENDING', help_text='وضعیت فعلی پیام', max_length=20, verbose_name='وضعیت')),
                ('sent_at', models.DateTimeField(blank=True, help_text='زمان ارسال پیام', null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='زمان تحویل پیام', null=True, verbose_name='زمان تحویل')),
                ('error_message', models.TextField(blank=True, help_text='پیام خطا در صورت عدم موفقیت', verbose_name='پیام خطا')),
                ('api_response', models.JSONField(default=dict, help_text='پاسخ دریافتی از سرور SMS', verbose_name='پاسخ API')),
                ('extra_data', models.JSONField(default=dict, help_text='اطلاعات اضافی مرتبط با پیام', verbose_name='اطلاعات اضافی')),
                ('user', models.ForeignKey(blank=True, help_text='کاربر مرتبط با پیام', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('template', models.ForeignKey(blank=True, help_text='قالب استفاده شده', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.smstemplate', verbose_name='قالب')),
            ],
            options={
                'verbose_name': 'پیام پیامک',
                'verbose_name_plural': 'پیام\u200cهای پیامک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('phone_number', models.CharField(help_text='شماره تلفن دریافت\u200cکننده', max_length=20, verbose_name='شماره تلفن')),
                ('verification_code', models.CharField(help_text='کد تایید 6 رقمی', max_length=6, verbose_name='کد تایید')),
                ('expires_at', models.DateTimeField(help_text='زمان انقضای کد تایید', verbose_name='زمان انقضا')),
                ('is_used', models.BooleanField(default=False, help_text='آیا کد تایید استفاده شده است', verbose_name='استفاده شده')),
                ('attempts', models.IntegerField(default=0, help_text='تعداد تلاش\u200cهای ناموفق', verbose_name='تعداد تلاش')),
                ('sms_message', models.ForeignKey(blank=True, help_text='پیام SMS مرتبط', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.smsmessage', verbose_name='پیام SMS')),
            ],
            options={
                'verbose_name': 'کد تایید SMS',
                'verbose_name_plural': 'کدهای تایید SMS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['phone_number'], name='sms_smsmess_phone_n_928a49_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['status'], name='sms_smsmess_status_4ce5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['message_type'], name='sms_smsmess_message_d73b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['tracking_id'], name='sms_smsmess_trackin_2c0af7_idx'),
        ),
        migrations.AddIndex(
            model_name='smsverification',
            index=models.Index(fields=['phone_number'], name='sms_smsveri_phone_n_4d6254_idx'),
        ),
        migrations.AddIndex(
            model_name='smsverification',
            index=models.Index(fields=['verification_code'], name='sms_smsveri_verific_f891ff_idx'),
        ),
    ]
