# Generated by Django 5.2.1 on 2025-07-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssettings',
            name='sms_fallback_to_fake',
            field=models.BooleanField(default=False, help_text='در صورت عدم دسترسی به سرور SMS، از fake SMS استفاده شود', verbose_name='فعال\u200cسازی fallback به fake SMS'),
        ),
    ]
