# Generated by Django 5.2.1 on 2025-07-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smssettings_sms_fallback_to_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssettings',
            name='sms_message_format',
            field=models.CharField(choices=[('standard', 'استاندارد'), ('compact', 'فشرده'), ('detailed', 'تفصیلی')], default='standard', help_text='فرمت پیام\u200cهای SMS', max_length=20, verbose_name='فرمت پیام SMS'),
        ),
    ]
