# Generated by Django 5.2.1 on 2025-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_requested_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logs',
            field=models.TextField(blank=True, default='', help_text='لاگ\u200cهای تحلیلی برای تیم آنالیتیکس (append only)', verbose_name='📝 لاگ\u200cها'),
        ),
        migrations.AddField(
            model_name='order',
            name='logs',
            field=models.TextField(blank=True, default='', help_text='لاگ\u200cهای تحلیلی برای تیم آنالیتیکس (append only)', verbose_name='📝 لاگ\u200cها'),
        ),
    ]
