# Generated by Django 5.2.1 on 2025-07-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customer_logs_order_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='is_official_holiday',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، فروشگاه به علت تعطیلی رسمی (مثلاً شهادت حضرت علی) بسته است.', verbose_name='تعطیل رسمی (ایران)'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='is_thursday_open',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، فروشگاه در روز پنج\u200cشنبه باز است.', verbose_name='آیا پنج\u200cشنبه باز است؟'),
        ),
    ]
