# Generated by Django 5.2.1 on 2025-07-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_workinghours_is_official_holiday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='is_official_holiday',
        ),
        migrations.AddField(
            model_name='workinghours',
            name='holiday_help_text',
            field=models.CharField(blank=True, help_text='متنی که به مشتری هنگام تعطیلی نمایش داده می\u200cشود (مثلاً: به علت شهادت حضرت علی تعطیل رسمی می\u200cباشد)', max_length=255, verbose_name='متن راهنما برای تعطیلی'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، فروشگاه به علت تعطیلی بسته است.', verbose_name='تعطیل (Holiday)'),
        ),
    ]
