# Generated by Django 5.2.1 on 2025-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_workinghours_max_selection_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', '💵 نقدی'), ('Terms', '📅 قسطی')], help_text='روش پرداخت انتخاب شده توسط مشتری', max_length=20, verbose_name='💳 روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment_method',
            field=models.CharField(choices=[('Cash', '💵 نقدی'), ('Terms', '📅 قسطی')], default='Cash', help_text='نوع پرداخت انتخابی برای این محصول', max_length=20, verbose_name='💳 نوع پرداخت'),
        ),
    ]
