# Generated by Django 5.2.1 on 2025-07-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='cash_purchases_disabled',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، مشتریان نمی\u200cتوانند محصولات را به صورت نقدی خریداری کنند', verbose_name='💰 غیرفعال کردن خرید نقدی'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', '✅ ایجاد'), ('UPDATE', '📝 ویرایش'), ('DELETE', '🗑️ حذف'), ('LOGIN', '🔑 ورود'), ('LOGOUT', '🚪 خروج'), ('EXPORT', '📤 خروجی'), ('IMPORT', '📥 ورودی'), ('APPROVE', '✅ تایید'), ('REJECT', '❌ رد'), ('PAYMENT', '💰 پرداخت'), ('ORDER', '🛒 سفارش'), ('DELIVERY', '🚚 تحویل'), ('CANCEL', '🚫 لغو'), ('RESTORE', '♻️ بازگردانی'), ('BACKUP', '💾 پشتیبان\u200cگیری'), ('PRICE_UPDATE', '💰 تغییر قیمت'), ('ERROR', '⚠️ خطا'), ('WARNING', '⚡ هشدار'), ('INFO', 'ℹ️ اطلاعات')], help_text='نوع عملیات انجام شده توسط کاربر', max_length=20, verbose_name='🎭 نوع عملیات'),
        ),
    ]
