# Generated by Django 5.2.1 on 2025-07-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='شماره تلفن تماس مشتری (همراه یا ثابت)', max_length=20, unique=True, verbose_name='📞 شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', '✅ فعال'), ('Inactive', '⏸️ غیرفعال'), ('Suspended', '🚫 معلق'), ('Blocked', '🔒 مسدود'), ('Requested', '📝 در انتظار تایید')], default='Active', help_text='وضعیت فعلی مشتری در سیستم', max_length=255, verbose_name='📊 وضعیت مشتری'),
        ),
    ]
