# Generated by Django 5.2.1 on 2025-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_workinghours_is_official_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='max_selection_limit',
            field=models.PositiveIntegerField(default=6, help_text='حداکثر تعداد محصولاتی که مشتری می\u200cتواند در یک بار انتخاب کند (پیش\u200cفرض: 6)', verbose_name='حداکثر تعداد محصولات قابل انتخاب'),
        ),
    ]
