# Generated by Django 5.2.1 on 2025-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldmapping',
            options={'verbose_name': 'Field Mapping', 'verbose_name_plural': 'Field Mappings'},
        ),
        migrations.AlterModelOptions(
            name='productmapping',
            options={'verbose_name': 'Product Mapping', 'verbose_name_plural': 'Product Mappings'},
        ),
        migrations.AlterModelOptions(
            name='syncconfig',
            options={'verbose_name': 'Sync Configuration', 'verbose_name_plural': 'Sync Configuration'},
        ),
        migrations.AlterModelOptions(
            name='synclog',
            options={'ordering': ['-executed_at'], 'verbose_name': 'Sync Log', 'verbose_name_plural': 'Sync Logs'},
        ),
        migrations.AlterField(
            model_name='fieldmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='fieldmapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='syncconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='syncconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی'),
        ),
    ]
